### ISSUE TITLE
How is this gem related to "capistrano/maintenance"?

### ISSUE THREAD

**Issue by groe** [tvdeyen/capistrano-maintenance#14]
How is this gem related to [capistrano/maintenance](https://github.com/capistrano/maintenance)?

Question is related to this issue: https://github.com/capistrano/maintenance/issues/29

Can this gem be used for capistrano 2 and 3?

**Comment by tvdeyen** [comment]
This gem was extracted from Capistrano 2 in times where Capistrano removed the functionality. But shortly after, the functionality was brought back to Capistrano 2. So this gem is not really necessary anymore. 

And no, it's not compatible with Capistrano 3.

**Comment by groe** [comment]
@tvdeyen Thanks for the quick response!

If this gem is not being used anymore, we could use the rubygems name "capistrano-maintenance" for the [capistrano 3 gem](https://github.com/capistrano/maintenance), could we? Right now, that gem has to be installed from git which is not ideal for version management and some production environments.

@kirs What's your opinion on that?

**Comment by tvdeyen** [comment]
I am totally fine with that. 

The only concern is: what do we do with users currently using my gem. If we simply replace the gems, then existing users will get in trouble. 

Although, only if they 'gem update' or 'bundle update', right?

You should use a version number higher, then my current version (0.0.4). I guess this should be ok. 

What do you think?

**Comment by groe** [comment]
Sounds good to me! I am not the maintainer of [capistrano/maintenance](https://github.com/capistrano/maintenance) though, so we would have to wait to wait for @kirs I guess.

**Comment by tvdeyen** [comment]
https://github.com/capistrano/maintenance/issues/29#issuecomment-99386090
